In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load sensors
selectedsensors = [ "sonycnode-b827eb0fedda.sonyc",
                    "sonycnode-b827eb42bd4a.sonyc",
#                     "sonycnode-b827eb44506f.sonyc",
#                     "sonycnode-b827eb73e772.sonyc",
#                     "sonycnode-b827eb74a519.sonyc",
#                     "sonycnode-b827eb84deb5.sonyc",
                    "sonycnode-b827ebb40450.sonyc"]

In [8]:
datapath = '../../rawdata/sensors/'
sensorMetadata = 'nodes.txt'

In [18]:
sensorsData = {}

file = open(sensors)
for line in file:
    s, lat, lon = line.split(' ')
    
    sensorData = pd.read_pickle(datapath + s + '.pkl')
    sensorsData[s] = sensorData
    
    break

,count,countWindow,hist,histExtraCount,histExtraSum,histWindow,max,min,sum,sum2,sumEq,ts
index,,,,,,,,,,,,
2018-01-01 00:00:00,3599,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",90.449997,56.889999,238467.281250,15877926.0,2.797035e+10,1514764800
2018-01-01 01:00:00,3600,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",105.209999,57.599998,245990.906250,16939476.0,2.315200e+11,1514768400
2018-01-01 02:00:00,3599,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",101.230003,56.820000,244179.343750,16685278.0,1.114228e+11,1514772000
2018-01-01 03:00:00,3600,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",89.139999,56.560001,238658.109375,15938863.0,3.367773e+10,1514775600
2018-01-01 04:00:00,3600,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",97.739998,56.240002,238072.640625,15884818.0,6.820722e+10,1514779200